#!/usr/bin/env bash
set -e
pushd ~/Repos/nixos-v1/
# nvim configuration.nix
# alejandra . &>/dev/null
git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch --flake . &>nixos-switch.log || (
 cat nixos-switch.log | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
# ask for confirmation and git push
read -p "Push the config to the repo? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Executing: git push"
    git push
fi
popd
