# file location: ~/.bashrc

# EXPORTS
# NOTE: might need to add some of those to the /etc/environment file to make them work system-wide

export XDG_DATA_HOME="$HOME"/.local/share
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_CACHE_HOME="$HOME"/.cache
export PS1="\[$(tput bold)\]\[\033[38;5;0m\]\[\033[48;5;11m\]\u\[$(tput sgr0)\] \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;255m\]\W\[$(tput sgr0)\]\[\033[38;5;11m\]>\[$(tput sgr0)\] \[$(tput sgr0)\]"
export EDITOR="nvim"
export ANDROID_HOME="$XDG_DATA_HOME"/android
export HISTFILE="$XDG_STATE_HOME"/bash/history
#export CARGO_HOME="$XDG_DATA_HOME"/cargo
#export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export KDEHOME="$XDG_CONFIG_HOME"/kde
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export PYTHONSTARTUP="$XDG_CONFIG_HOME"/python/pythonrc
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
#export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
#export CARGO_TARGET_DIR="$HOME"/Programming/CargoTarget # might want to add this to /etc/environment but with an absolute path

alias cp='cp -i'                          # confirm before overwriting something
alias more=less
alias ls='ls --color=auto'
alias l='ls --color=auto'
alias ll='ls -lah --color=auto'
alias c='cd'
alias ip='ip --color=auto'
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
alias sudo='sudo '                        # this makes the aliases with with sudo
#alias fixscreen='sxiv -fb /home/dvdmanjaro/Desktop/Files/black.jpg'
alias alpvm='docker run --rm -it alpine'
#alias threebe='cd /home/dvdmanjaro/Desktop/Programming/Docker/Git/Threebe; code /home/dvdmanjaro/Desktop/Programming/Docker/Git/Threebe'
#alias alpssh='alpsshname=$(docker run --rm -d -t alpine); docker exec -t $alpsshname apk add openssh; docker exec -it $alpsshname sh'
#alias hostVPNadd='nmcli connection delete client-wg0; nmcli connection import type wireguard file /home/dvdmanjaro/Desktop/Hacking/others/vps/client-wg0.conf; nmcli con mod client-wg0 connection.autoconnect no'
#alias hostVPNedit='echo "" > /home/dvdmanjaro/Desktop/Hacking/others/vps/client-wg0.conf; nano /home/dvdmanjaro/Desktop/Hacking/others/vps/client-wg0.conf'
#alias VPNon='python3 /home/dvdmanjaro/Desktop/Hacking/others/vps/tkScripts.py & alpssh; hostVPNedit; hostVPNadd; kill -9 $(ps aux | grep tkScripts | grep -v grep | awk "{print \$2}"); clear'
#alias VPNoff='wg-quick down /home/dvdmanjaro/Desktop/Hacking/others/vps/client-wg0.conf; clear'
#alias VPSon='python3 /home/dvdmanjaro/Desktop/Hacking/others/vps/tkScripts.py & alpssh; kill -9 $(ps aux | grep tkScripts | grep -v grep | awk "{print \$2}"); clear'
alias startdocker='sudo systemctl start docker'
#alias dockergui='docker run --rm -it -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix archlinux'
alias cachec='sudo bash -c "sync; echo 3 > /proc/sys/vm/drop_caches"'
alias gamingcont='docker run --rm -it -e DISPLAY --ipc=host --device /dev/dri/card0 -v /dev/input:/dev/input -v /etc/machine-id:/etc/machine-id -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/snd -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native -v ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR} --group-add audio -v ~/.config/pulse/cookie:/root/.config/pulse/cookie --privileged archlinux'
alias gamingcontsock='docker run --rm -it -e DISPLAY --ipc=host -e XDG_RUNTIME_DIR --device /dev/dri/card0 -v /etc/machine-id:/etc/machine-id -v /dev/input:/dev/input -v /tmp/.X11-unix:/tmp/.X11-unix --device /dev/snd -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native --group-add audio -v ~/.config/pulse/cookie:/root/.config/pulse/cookie -v ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR} --privileged archlinux'
alias music_prod='docker start "music_prod" &>/dev/null; docker exec -it "music_prod" bash && docker stop "music_prod" &>/dev/null'
alias contcp='bash ~/Desktop/Files/SomeScripts/contcp.sh'
alias pyserv='python3 -m http.server 8080'
alias luaserv='luajit -e "require(\"seclib\").http.server(8080, \"0.0.0.0\")"'
alias vim='nvim'
alias v='nvim'
alias vi='nvim --noplugin -u /etc/xdg/nvim/sysinit.vim'
alias vimg='neovide --multigrid'
alias up='paru; flatpak update; rustup update'
alias venv='virtualenv'

gaming_func () {
    # Mounting win drive if it's not already
    if [ "$(ls -A ~/Others/WinMount/)" ]; then
        : # already mounted
    else
        echo "Mounting win drive..."
        sudo mount -t ntfs -o ro /dev/sda2 ~/Others/WinMount/
    fi
    docker start "gaming_container" &>/dev/null; docker exec -u user -it "gaming_container" bash; docker stop "gaming_container" &>/dev/null
}

alias gaming='gaming_func'

xhost +local:root > /dev/null 2>&1

# vim input mode for the shell
# set -o vi

shopt -s checkwinsize
shopt -s expand_aliases
# Enable history appending instead of overwriting.  #139609
shopt -s histappend

source "$HOME"/.cargo/env
